### ISSUE TITLE
Bug with Numbered Lists and Bulleted Lists 

### ISSUE THREAD

**Issue by josh-egan** [notslang/tidy-markdown#11]
There appears to be a bug with list handling. I am using [atom-beautify](https://atom.io/packages/atom-beautify) in [atom](https://atom.io/), which is using tidy-markdown for markdown support. 

If I start with this:

```
1. Do this first
2. And then this

- Bucket
- List
```

The first time I run tidy-markdown, I get this:

```
1. Do this first
- And then this
- Bucket
2. List
```

The above renders to a numbered list when parsed. So, as expected, the markdown is converted to this when I run tidy-markdown a second time:

```
1. Do this first
2. And then this
3. Bucket
4. List
```

Nested lists are handled correctly. The following is not modified when tidy-markdown is run.

```
1. Do this first
2. And then this
  - Bucket
  - List
```

It seems the solution to this would be to differentiate between numbered lists and bulleted lists and not attempt to merge them.

**Comment by slang800** [comment]
ah, yes... this is a flaw in markdown itself:

![screenshot from 2015-06-06 00 39 47](https://cloud.githubusercontent.com/assets/1049204/8018322/8bd55c5c-0be4-11e5-8b86-5bae8b2ee821.png)

also: ref #7 

I think I'm just going to switch to a common-markdown compliant parser
