### ISSUE TITLE
language-code-rewrites.json missing from 2.0.5

### ISSUE THREAD

**Issue by wavded** [notslang/tidy-markdown#50]
Had to downgrade to 2.0.4 in order to get it work again.

**Comment by wavded** [comment]
Actually I think all the `.json` files in the `lib/` directory were missing.

**Comment by nukeop** [comment]
Same problem, release 2.0.5 is broken.

**Comment by szeck87** [comment]
@slang800 any plan to republish 2.0.5 to npm with a fix for this?

**Comment by stoplion** [comment]
+1

**Comment by lcherone** [comment]
+1

**Comment by bhudgens** [comment]
Couldn't get this working out of npm. I've pinned to 2.0.4 on my fork which got it working again.

`npm i [-g] bhudgens/tidy-markdown`
