### ISSUE TITLE
[query] Is output valid CommonMark?

### ISSUE THREAD

**Issue by david-libremone** [notslang/tidy-markdown#53]
Do you make any guarantees that the output conforms to the CommonMark spec? It doesn't look like it, just thought I'd confirm.

I understand that a document with tables obviously wouldn't conform (last I checked tables weren't in CommonMark).

**Comment by notslang** [comment]
I don't make any guarantees about it, but I'm planning on switching over to a CommonMark parser at some point, and I would glady take PRs that improve CommonMark compliance.
